name: run-script
on: 
  workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: script
    run: PATH/AddColab.sh
    shell: bash
    with:
    password: ${{ secrets.TOKEN }}
